### PR TITLE
2017 data update

### PR DESCRIPTION
**Pull request by Rossolson**
The conversion script is totally optional of course, but I thought it might help the next time this is updated, if the update comes from the same agency. I'm not sure if SEMVER would have this as a breaking change or a bugfix, so I split the difference.

### CODE REVIEW

**Review by vintesh — APPROVED** [review]
Looks good to me! Except I haven't checked the `.sh` file, but as it won't harm & I believe you..! 😆 
Just one thing, when you merge, use Squash n Merge option.

**Comment by vintesh** [comment]
@NickCarneiro you might want to take a look & publish.

**Comment by NickCarneiro** [comment]
Great work! I'll merge and publish now.

Going forward we should designate someone else to be the lead maintainer of this package. I haven't used it in years and I don't want my non-responsiveness to slow down other developers.

**Comment by Rossolson** [comment]
@vintesh & @NickCarneiro I'm glad you felt that this was worthy of bringing in. I updated this even though it looks like our company isn't going to use it (another team already has a similar dataset) but it looked like a fun update. @vintesh Your suggestion for Squash n Merge is well taken. In this case I wanted Nick to be able to pull apart the individual changes if he wanted. Adding a non-production shell script might have been more than he wanted to have as part of the project.

**Pull request merged**
